insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Toy-Feest', 'Portugal', 2012, 63, 450, 'Cordell Jacquet', 43);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Rutherford, Schinner and Hackett', 'Portugal', 1992, 35, 160, 'Jacenta Este', 91);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Howe, Ratke and Goyette', 'France', 1987, 2, 238, 'Rudiger Frowd', 14);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Botsford, Goyette and Heathcote', 'France', 2008, 108, 465, 'Natka Sailes', 3);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Blanda-Swaniawski', 'Portugal', 2008, 93, 65, 'Vernen Friett', 36);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Senger-Reilly', 'Portugal', 1998, 33, 299, 'Dorelia Frudd', 98);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Koss-Wyman', 'Portugal', 1995, 19, 32, 'Margi Muck', 2);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kunde Inc', 'France', 1993, 19, 196, 'Moyra Vedenichev', 67);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Senger, Lubowitz and Ledner', 'France', 2011, 102, 797, 'Elbertine Danko', 58);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Marquardt Group', 'Portugal', 2011, 19, 404, 'Hertha Kaubisch', 38);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mohr and Sons', 'France', 2010, 100, 968, 'Lil Burgess', 49);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hodkiewicz Inc', 'Portugal', 1997, 20, 484, 'Nina Broxup', 42);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Monahan LLC', 'Germany', 1999, 48, 630, 'Clarence Terbeek', 5);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Johns-Ledner', 'Portugal', 2012, 57, 476, 'Carlota Croneen', 20);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kilback-Boyer', 'France', 1997, 69, 345, 'Maddy Tidball', 49);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Price, Fritsch and Schmeler', 'Portugal', 2011, 96, 863, 'Nobe Coppledike', 76);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Jacobs, Ondricka and Doyle', 'Portugal', 2012, 76, 945, 'Felix Sharrock', 33);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Funk, White and Dietrich', 'Portugal', 1993, 93, 307, 'Darsie McKilroe', 4);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Conn-O''Kon', 'France', 1999, 48, 966, 'Emmi Perkins', 95);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('West LLC', 'France', 2010, 4, 206, 'Fredericka Webben', 97);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Goyette, Sauer and Green', 'France', 1996, 44, 529, 'Joana Girardengo', 64);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Goyette LLC', 'Portugal', 2005, 85, 300, 'Mead Benedicto', 46);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Wiegand-Dibbert', 'France', 2010, 36, 766, 'Esther Sand', 51);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Christiansen, McDermott and Waters', 'Portugal', 2000, 86, 385, 'Clerkclaude Clerk', 97);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('DuBuque-Gleichner', 'France', 1986, 59, 789, 'Sim Seabrocke', 84);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Franecki, Stroman and Rutherford', 'Portugal', 2004, 101, 568, 'Carmita Hebden', 55);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Block, Stark and Fay', 'Portugal', 2012, 108, 430, 'Fancy Threlfall', 52);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Dietrich, Miller and Hyatt', 'France', 2012, 53, 994, 'Lillian Cottell', 100);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Howe Inc', 'France', 2005, 104, 448, 'Teodorico Enderwick', 95);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Nienow, Prohaska and Willms', 'Portugal', 2009, 94, 471, 'Gabi Gionettitti', 18);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Tillman, Turcotte and Mraz', 'Spain', 2012, 13, 880, 'Amye Webber', 76);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Lubowitz and Sons', 'Portugal', 2010, 3, 432, 'Margo Butlin', 85);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hills, Johns and Botsford', 'Portugal', 2011, 109, 288, 'Faydra Helder', 17);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Fahey Inc', 'Portugal', 2000, 53, 43, 'Adina Dade', 84);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Leuschke-Balistreri', 'Germany', 1998, 107, 716, 'Cynthea Hillatt', 71);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Ward-Sawayn', 'Portugal', 2012, 22, 245, 'Sharon Phaup', 22);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Olson and Sons', 'Spain', 1992, 7, 602, 'Ellis Bampford', 32);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Carroll, Pollich and Prosacco', 'Portugal', 1988, 108, 768, 'Arlina Blakeslee', 80);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Pfannerstill and Sons', 'Portugal', 1997, 5, 538, 'Rudolfo Coleridge', 96);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kuhlman, MacGyver and Aufderhar', 'Portugal', 2008, 4, 297, 'Zahara Scutts', 72);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Reinger, Sauer and Schultz', 'Portugal', 1999, 89, 743, 'Viole Pickrill', 55);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hammes LLC', 'France', 2006, 96, 758, 'Odelle Rosnau', 96);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('O''Conner-VonRueden', 'Portugal', 2002, 108, 35, 'Agata Turl', 55);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Reinger, Johnston and Feil', 'France', 2007, 8, 972, 'Nesta Norquoy', 31);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schuppe Group', 'Portugal', 1996, 38, 883, 'Avis Dunford', 82);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Deckow Inc', 'France', 2011, 41, 912, 'Kathi Walesa', 49);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Lowe, Marvin and Grant', 'Portugal', 2004, 40, 604, 'Sybilla Gowrich', 56);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Ratke and Sons', 'Portugal', 1986, 39, 387, 'Olenolin Fair', 22);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Glover-Ledner', 'France', 2002, 64, 395, 'Stinky Tosspell', 38);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kuhn, Goyette and Casper', 'Spain', 1993, 9, 184, 'Lynda Dubock', 20);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Casper LLC', 'France', 2001, 108, 679, 'Hardy Hickenbottom', 88);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Haley-Schneider', 'Spain', 2005, 64, 9, 'Rubin Gerrill', 95);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hermann LLC', 'United Kingdom', 2012, 2, 932, 'Corinne Busch', 79);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Jenkins, Blick and Koss', 'Portugal', 2011, 110, 327, 'Sky Gumn', 44);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Gibson Inc', 'Portugal', 2003, 114, 441, 'Rochella Segge', 77);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Marvin-McCullough', 'France', 2012, 77, 386, 'Sharlene Nussgen', 3);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bartell Inc', 'Spain', 1987, 65, 69, 'Adela Hodges', 31);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Fadel LLC', 'Portugal', 2000, 44, 771, 'Hebert Gabbotts', 30);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Wolff-Dach', 'France', 2005, 4, 218, 'Ricky Taber', 41);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Sauer-Crona', 'Portugal', 2009, 94, 96, 'Ilyssa McLucky', 84);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Gerlach, Brakus and Bosco', 'Portugal', 1995, 19, 567, 'Venita Horry', 46);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('VonRueden, Cruickshank and Kunde', 'France', 2004, 59, 489, 'Wilton Cyphus', 96);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bahringer Inc', 'France', 1996, 78, 177, 'Kit Garter', 38);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Roberts LLC', 'United Kingdom', 1996, 101, 267, 'Salvatore Callen', 93);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Feil Group', 'United Kingdom', 2000, 23, 151, 'Hinda Mattessen', 65);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bartell, Monahan and Breitenberg', 'France', 2011, 83, 814, 'Karin Geary', 34);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Cole and Sons', 'Germany', 2011, 63, 156, 'Alister Clogg', 18);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hegmann Inc', 'Portugal', 1995, 74, 447, 'Valerye Sabathier', 88);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Weimann, Senger and Nitzsche', 'France', 2000, 90, 54, 'Brigit Bohling', 87);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Jacobi-Russel', 'Switzerland', 1993, 27, 831, 'Edgard Woolvett', 30);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Douglas-Becker', 'France', 1997, 92, 833, 'Stephanus O'' Cuolahan', 9);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Sipes Inc', 'France', 2004, 59, 995, 'Valentijn Prop', 14);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kuhlman, Gusikowski and Runolfsdottir', 'France', 1994, 103, 319, 'Clarence Pietersen', 69);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('McLaughlin-Mosciski', 'Belgium', 2012, 95, 359, 'Antonius Hoonahan', 82);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Sanford-Deckow', 'France', 2000, 97, 841, 'Phoebe Arthurs', 80);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Beer, Pacocha and Hyatt', 'France', 2006, 110, 692, 'Franciskus Tesimon', 48);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Gutmann-Kutch', 'France', 2010, 6, 333, 'Tessa Neal', 13);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Emard-Nicolas', 'United Kingdom', 2000, 16, 864, 'Barde Eliff', 28);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Feil, Tremblay and Goyette', 'Portugal', 2004, 35, 453, 'Dehlia Divine', 28);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Frami-Deckow', 'France', 2007, 46, 139, 'Park Alentyev', 7);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Grady, Lind and Hartmann', 'Portugal', 2004, 47, 23, 'Philbert Eldredge', 93);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Rempel Inc', 'France', 2000, 103, 895, 'Corella Strute', 95);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Brekke LLC', 'Portugal', 1984, 18, 983, 'Leyla Abrahamsen', 36);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Olson, Upton and Heathcote', 'France', 2013, 76, 179, 'Alisun Yon', 81);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kozey, Mitchell and Wisozk', 'Germany', 1995, 81, 439, 'Teresa Surmeyer', 27);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('McLaughlin LLC', 'Portugal', 2004, 72, 56, 'Alfy Semkins', 51);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Auer, Hills and Kertzmann', 'Portugal', 1964, 100, 816, 'Clemente MacGaughey', 24);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bahringer, O''Connell and O''Keefe', 'Portugal', 2012, 47, 793, 'Claiborn Gabriel', 40);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Corwin-Stokes', 'Portugal', 2012, 25, 876, 'Thedric Oke', 25);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schmeler-Jast', 'France', 1971, 90, 535, 'Annadiana Kinavan', 38);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bayer, Rath and Carroll', 'France', 1987, 104, 243, 'Angelia Chittock', 51);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schowalter-Bradtke', 'Portugal', 1995, 78, 963, 'Sioux Burehill', 39);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Morissette and Sons', 'Portugal', 1993, 47, 233, 'Vivien Davio', 10);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Gusikowski-Donnelly', 'Portugal', 2007, 111, 900, 'Anet Gunson', 20);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Eichmann-Boyle', 'France', 1987, 101, 337, 'Isiahi Sutehall', 54);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Marks-Grant', 'France', 2007, 109, 638, 'Con Lyokhin', 85);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Ebert, Nolan and Kiehn', 'France', 1993, 37, 544, 'Brittne Itchingham', 54);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kreiger, Stamm and Leuschke', 'Portugal', 2004, 99, 473, 'Sada Pettit', 57);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Prosacco Inc', 'Portugal', 2011, 45, 145, 'Ailsun Braddock', 73);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Cronin-Wyman', 'France', 1999, 82, 123, 'Kim Dedden', 76);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Predovic Group', 'France', 2012, 33, 825, 'Madeline Mintrim', 94);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Ziemann, Barton and Powlowski', 'Portugal', 2002, 47, 916, 'Oralle Germon', 42);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mosciski, Donnelly and Welch', 'Portugal', 2006, 51, 396, 'Ephrayim Thon', 7);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Boehm, Mosciski and Bergstrom', 'France', 1992, 71, 52, 'Delly Stobbie', 6);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Parker and Sons', 'Portugal', 1987, 9, 121, 'Helli Rookeby', 49);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Abshire Inc', 'France', 2007, 36, 972, 'Darwin Gillespey', 41);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Pagac-Effertz', 'France', 2008, 81, 780, 'Erny Ibanez', 8);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bergnaum-Grady', 'Germany', 2006, 87, 722, 'Fulton Felix', 33);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Buckridge, Ortiz and Fritsch', 'Portugal', 2005, 92, 924, 'Sher Verlander', 45);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('King, Gleason and Haley', 'Portugal', 2001, 62, 571, 'Stoddard Tyreman', 73);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Tromp-Terry', 'France', 1997, 93, 859, 'Jeremie Burgisi', 23);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('McCullough Inc', 'France', 1997, 54, 875, 'Cyrille Dufoure', 2);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Okuneva Inc', 'France', 1995, 55, 197, 'Micaela Varne', 6);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kulas, Ortiz and Walsh', 'Portugal', 1993, 57, 761, 'Eadie Flowers', 1);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mraz, Jakubowski and Ziemann', 'Portugal', 2013, 32, 327, 'Angy Olivas', 90);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bins and Sons', 'Portugal', 1999, 108, 945, 'Gunter Callf', 93);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bruen, Russel and Thompson', 'Germany', 2011, 7, 638, 'Jo Beetham', 38);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Parker-Barrows', 'France', 2012, 77, 830, 'Damara Elie', 47);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bechtelar, Barton and Rosenbaum', 'France', 1985, 40, 921, 'Hana Lovegrove', 25);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Swaniawski-D''Amore', 'France', 2004, 28, 830, 'Orland Beran', 43);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Swaniawski-Will', 'Portugal', 2001, 73, 652, 'Justis Dollin', 11);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kessler-Klocko', 'France', 2009, 79, 412, 'Mercy Rumgay', 29);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Casper Inc', 'Spain', 1995, 77, 515, 'Sheba Mattheus', 94);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Ferry, Rath and Ankunding', 'Portugal', 2005, 7, 527, 'Vannie Ransbury', 22);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bechtelar-Greenfelder', 'Portugal', 2009, 28, 628, 'Dani Shipman', 38);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('McCullough-Grady', 'Portugal', 1993, 104, 486, 'Trisha Schruyer', 80);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Harber Inc', 'France', 2011, 66, 771, 'Deanne Ravenscraft', 67);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Luettgen, Cummerata and Schowalter', 'Portugal', 1992, 85, 674, 'Martie Meeus', 3);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Treutel-Nolan', 'Portugal', 1999, 4, 972, 'Tedmund Lydiate', 54);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Thiel Inc', 'Portugal', 1986, 61, 68, 'Deanna Deelay', 5);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Breitenberg Inc', 'France', 2010, 8, 566, 'Dian Aimeric', 60);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Harris, Ortiz and Renner', 'Portugal', 1999, 45, 54, 'Turner Yeabsley', 39);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Klein, Cremin and Dicki', 'France', 2008, 17, 561, 'Aimee Skitral', 79);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Senger, DuBuque and Vandervort', 'France', 2007, 45, 97, 'Mab Smewin', 15);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mitchell Inc', 'Portugal', 2007, 77, 301, 'Sibylle Renfield', 32);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Crooks, Glover and Rodriguez', 'France', 1993, 115, 305, 'Gussie Shone', 75);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hilpert, Waters and Littel', 'France', 1996, 106, 208, 'Robin Lukes', 26);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hagenes, Mohr and McGlynn', 'Portugal', 2000, 105, 267, 'Ranice Lowdham', 55);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Stiedemann-Langosh', 'France', 2007, 95, 599, 'Binny Pethick', 25);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kiehn, Senger and Wolff', 'Portugal', 2001, 45, 633, 'Cal Brampton', 2);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kuhn Inc', 'Portugal', 2003, 91, 236, 'Mufinella Schapiro', 44);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Heaney LLC', 'Germany', 2012, 72, 764, 'Karlan Blake', 30);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Upton-Weber', 'Portugal', 1994, 26, 720, 'Fawnia Stollwerk', 88);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('DuBuque-O''Reilly', 'Portugal', 2009, 67, 552, 'Martynne Goodenough', 6);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Heathcote, Durgan and Klocko', 'France', 1999, 114, 489, 'Gabriell Newson', 96);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Lowe and Sons', 'France', 2009, 95, 992, 'Rita Camis', 54);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Jones Inc', 'France', 1994, 53, 215, 'Jephthah Toping', 90);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Durgan-Larkin', 'Portugal', 1992, 26, 705, 'Carri Moggan', 56);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Padberg, Will and Schiller', 'France', 2007, 1, 388, 'Zach Napoleon', 91);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mayer-VonRueden', 'Germany', 2007, 41, 945, 'Kathleen Bissett', 2);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Sporer-Legros', 'Portugal', 1998, 95, 208, 'Darrell Abraham', 67);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mante, Murazik and Corwin', 'Portugal', 2008, 51, 275, 'Harp Domerq', 93);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Dibbert-Torphy', 'Portugal', 1999, 53, 964, 'Kermie Brandes', 39);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hegmann-Spencer', 'Portugal', 2011, 102, 464, 'Forster Ridgewell', 74);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Gutkowski, Walter and Satterfield', 'Portugal', 1967, 80, 75, 'Phaedra Farrar', 89);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Sipes LLC', 'Portugal', 1996, 90, 2, 'Abel Naismith', 28);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hahn, Howell and Collins', 'France', 2013, 3, 26, 'Cass Kort', 64);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hyatt LLC', 'France', 1993, 69, 750, 'Merla Keppie', 61);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kessler LLC', 'France', 1993, 14, 411, 'Cristina Fearon', 95);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Ledner, Koepp and Rath', 'Portugal', 2010, 31, 39, 'Michelle Growcott', 73);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Nienow and Sons', 'France', 1984, 59, 724, 'Dedra Baumaier', 23);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kub Inc', 'France', 2004, 3, 14, 'Audrie Aarons', 2);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Johnston Group', 'France', 2004, 6, 562, 'Marin Overshott', 57);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schulist, D''Amore and Simonis', 'France', 1999, 63, 171, 'Ethelin Kobke', 48);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Witting-Hahn', 'France', 1997, 36, 864, 'Vidovik Horder', 69);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Streich LLC', 'Portugal', 1988, 15, 766, 'Karole Kippen', 89);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Marquardt, Nolan and Dicki', 'France', 2005, 56, 344, 'Olympe Pontin', 60);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mante-Braun', 'France', 2009, 87, 757, 'Ynes Hanshawe', 51);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bergstrom, Gerlach and Morissette', 'Portugal', 2009, 91, 601, 'Garwin Sexty', 53);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Weissnat Group', 'Portugal', 1994, 104, 665, 'Bunni Castille', 28);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Champlin, Miller and Cassin', 'Portugal', 2003, 89, 906, 'Edee Lund', 73);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Rohan-Bode', 'Portugal', 2012, 96, 757, 'Corabel Caldecutt', 8);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mills-Davis', 'Portugal', 2004, 86, 84, 'Gisela Powling', 69);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Brakus-Littel', 'Portugal', 1984, 65, 120, 'Minette Sugg', 65);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schamberger, Grimes and Hintz', 'Portugal', 2008, 103, 310, 'Lorianne Tatlowe', 52);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Heidenreich-Quitzon', 'Portugal', 2002, 114, 153, 'Amory Lonnon', 14);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Gorczany Inc', 'Germany', 1994, 43, 797, 'Mariya Head', 83);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Reichel-O''Reilly', 'France', 2012, 104, 844, 'Valentia Le Marchant', 98);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Baumbach, Rosenbaum and Witting', 'France', 2005, 107, 193, 'Roderick Mirfield', 62);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bergstrom, DuBuque and Wunsch', 'Portugal', 1991, 106, 227, 'Marybeth Fowden', 74);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Funk, Wuckert and Koelpin', 'Portugal', 1989, 32, 114, 'Merla Rangle', 30);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Batz, Wintheiser and Hansen', 'France', 1994, 38, 63, 'Emelina Loveday', 80);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Murazik LLC', 'Spain', 2010, 19, 493, 'Georgiana Mityushkin', 81);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bergnaum Group', 'France', 1998, 43, 814, 'Barnard Scurrell', 85);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('McDermott-Feil', 'Portugal', 1997, 66, 291, 'Stormy Suddards', 48);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Nicolas-Wolff', 'France', 2012, 55, 475, 'Leigh Mcimmie', 59);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Christiansen and Sons', 'France', 2008, 27, 595, 'Virginie Nuss', 71);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Cummerata Inc', 'Germany', 1996, 22, 250, 'Burg Heimes', 87);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Jacobson-Cummerata', 'Portugal', 2009, 75, 598, 'Kev Tremayne', 99);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bartell-Turcotte', 'Portugal', 2008, 15, 633, 'Anestassia Ferrucci', 66);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Okuneva, Goyette and Reichert', 'France', 1999, 27, 112, 'Arley Rickerby', 7);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Cremin-McLaughlin', 'Spain', 2013, 88, 858, 'Helsa Huckfield', 24);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Friesen, Pagac and Kautzer', 'Portugal', 1988, 27, 430, 'Tessy Snaddin', 19);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Barrows-Toy', 'Portugal', 2008, 66, 892, 'Shela Balint', 52);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Breitenberg-Koelpin', 'Portugal', 2003, 1, 834, 'Bailey Baulch', 69);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mosciski and Sons', 'France', 1995, 28, 494, 'Hedi Ismirnioglou', 95);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Conroy Inc', 'Portugal', 2010, 50, 958, 'Deirdre Freckleton', 96);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Koch and Sons', 'Portugal', 2010, 89, 240, 'Kurt Phizakarley', 52);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hagenes LLC', 'France', 2006, 92, 142, 'Hildy Penton', 64);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Luettgen-Rau', 'Portugal', 1967, 78, 238, 'Saw Konzelmann', 45);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Walter-Haag', 'France', 1998, 15, 602, 'Sisile Physick', 59);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Cole-Mraz', 'Portugal', 1988, 3, 218, 'Valentine Bradick', 81);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Langworth-Davis', 'France', 1998, 78, 480, 'Willie Martynka', 28);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Abernathy Inc', 'Portugal', 2000, 115, 291, 'Lou Vince', 13);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Batz Inc', 'France', 1999, 29, 5, 'Josefa Lange', 52);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Hintz Inc', 'Portugal', 2006, 106, 78, 'Micki Leates', 25);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Weber Group', 'France', 1997, 81, 102, 'Collie Hirtzmann', 5);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Marquardt Group', 'Portugal', 2004, 107, 67, 'Morgan Murrell', 30);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Lehner LLC', 'Germany', 2008, 41, 919, 'Rose Hanington', 37);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Roberts LLC', 'Germany', 1995, 29, 680, 'Karlen Assel', 3);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schmeler Inc', 'France', 2010, 1, 58, 'Malchy Osipenko', 79);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Ondricka LLC', 'France', 2012, 80, 964, 'Cindra Bellward', 54);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Wiegand and Sons', 'Portugal', 2001, 29, 905, 'Wald Tumber', 39);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Pacocha LLC', 'France', 1994, 79, 370, 'Oberon Aikenhead', 18);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Turner-Wunsch', 'Portugal', 1998, 64, 666, 'Ardyth De Ruggero', 78);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Boyer-Zieme', 'France', 2012, 25, 851, 'Griffin Vain', 88);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Purdy-Kshlerin', 'Portugal', 1989, 24, 275, 'Rusty Chisolm', 96);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Krajcik, Gulgowski and Padberg', 'France', 1993, 113, 954, 'Giles Hoofe', 7);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Mante-Dare', 'France', 2005, 101, 917, 'Rex Sherwen', 28);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Conroy-Wyman', 'France', 2006, 25, 426, 'Eimile Streather', 95);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Cormier LLC', 'Germany', 1997, 109, 631, 'Arri Schuck', 82);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Wiegand Group', 'France', 2007, 17, 759, 'Brina Van Halle', 97);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Prosacco LLC', 'Germany', 1970, 10, 65, 'Deni Cisson', 58);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Stracke Inc', 'Spain', 1991, 86, 695, 'Euell Leyborne', 51);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schroeder Group', 'Portugal', 1950, 77, 938, 'Tatum Radbond', 100);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Huel Inc', 'France', 2009, 4, 671, 'Calli Lydford', 94);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Schiller, Quigley and Goodwin', 'Spain', 1999, 87, 969, 'Terra Goreisr', 1);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Quitzon, Connelly and Kshlerin', 'Portugal', 2005, 84, 678, 'Jennette Cabane', 33);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kuphal, Bednar and Sipes', 'France', 2012, 80, 905, 'Celie Rean', 9);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Powlowski Group', 'France', 1996, 101, 613, 'Corie Culver', 90);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Wintheiser-Bechtelar', 'Portugal', 2012, 16, 690, 'Kally Gerardet', 88);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Volkman, Boyer and Stiedemann', 'Portugal', 2007, 74, 101, 'Simeon Cunney', 13);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kihn and Sons', 'France', 1998, 96, 266, 'Earlie Gorusso', 35);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bartoletti-Koepp', 'Portugal', 1991, 87, 882, 'Corbin Matijevic', 52);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Friesen Group', 'France', 2008, 63, 398, 'Grier Maccaig', 58);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Casper-Schamberger', 'France', 1998, 93, 215, 'Maurise Petrecz', 30);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Carter, Herzog and Koelpin', 'France', 1998, 37, 544, 'Whitaker Cheales', 84);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kassulke-Hammes', 'France', 2011, 58, 691, 'Aloysia Norquay', 36);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Wilderman, Cremin and Kuhlman', 'France', 2011, 114, 912, 'Ernst Vokins', 90);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Sauer, Hammes and Turcotte', 'France', 1997, 29, 407, 'Francisca Cheyenne', 80);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Leannon Group', 'France', 1993, 41, 906, 'Neda Giacoboni', 77);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Welch-Stroman', 'Portugal', 2003, 12, 899, 'Ricca Leacock', 85);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Treutel, MacGyver and Kassulke', 'Germany', 2005, 97, 377, 'Allys Bevir', 45);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Rempel-Nitzsche', 'Portugal', 1992, 69, 391, 'Launce Vawton', 63);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Bayer-Greenholt', 'France', 1992, 86, 208, 'Farlay Steanson', 80);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Kshlerin-Howe', 'France', 1994, 75, 932, 'Deloria Venturoli', 87);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Rowe-Robel', 'France', 1979, 4, 709, 'Erin Wimpeney', 33);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Nader-Stehr', 'Portugal', 2011, 58, 724, 'Marena Minichi', 18);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Rice Group', 'France', 1974, 108, 225, 'Tine Pethick', 89);
insert into teams (name, country, F1since, victoryNumber, nbrGP, president, headquarter_id) values ('Zulauf and Sons', 'Portugal', 2005, 88, 785, 'Ally Polak', 53);
