insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('quam', 'France', 'Pau', 6, 8, 2000);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('turpis', 'Portugal', 'Salvador', 3, 15, 2005);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('duis', 'Portugal', 'Gândara de Aquém', 5, 19, 2007);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('vel', 'Germany', 'Hamburg', 3, 12, 2006);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('nisi', 'France', 'Montaigu', 5, 18, 2004);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('quisque', 'France', 'La Rochelle', 8, 5, 2000);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('sit', 'France', 'Paris 08', 6, 18, 2007);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('odio', 'Portugal', 'Gondifelos', 7, 9, 1999);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('suspendisse', 'Portugal', 'Regueiro', 6, 6, 2005);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('nulla', 'France', 'Toulon', 7, 18, 2007);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('mi', 'Portugal', 'Entradas', 6, 6, 2005);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('ligula', 'Portugal', 'Limeiras', 3, 17, 2000);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('lacinia', 'Portugal', 'Fundão', 8, 16, 1993);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('ipsum', 'Portugal', 'Passagem', 6, 20, 2001);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('ut', 'France', 'Épinal', 8, 18, 2007);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('commodo', 'Portugal', 'Pedreira', 4, 7, 2006);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('quam', 'Portugal', 'Pereiras', 8, 12, 1992);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('semper', 'Portugal', 'Lemende', 4, 17, 2008);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('est', 'Portugal', 'Caldas das Taipas', 8, 14, 2003);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('donec', 'France', 'Dunkerque', 6, 17, 1987);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('eget', 'Portugal', 'Vila Nova da Baronia', 7, 11, 1993);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('vel', 'Portugal', 'Gonça', 5, 6, 1992);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('nec', 'France', 'Villeneuve-la-Garenne', 6, 9, 1997);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('nisl', 'Portugal', 'Rego de Água', 6, 20, 1994);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('in', 'Portugal', 'Santo Adrião Vizela', 4, 6, 2000);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('sociis', 'Germany', 'Cottbus', 3, 10, 2001);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('a', 'France', 'Nanterre', 5, 7, 1986);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('eu', 'France', 'Marne-la-Vallée', 4, 12, 2011);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('metus', 'France', 'Blois', 3, 8, 2006);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('nunc', 'France', 'Roanne', 6, 11, 1970);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('congue', 'Germany', 'Hamburg', 8, 18, 1990);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('massa', 'France', 'Paris 18', 8, 8, 2005);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('duis', 'Germany', 'Hamburg', 5, 5, 1993);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('non', 'Switzerland', 'Thun', 7, 7, 2009);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('est', 'France', 'Marne-la-Vallée', 7, 12, 2012);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('massa', 'France', 'Strasbourg', 5, 14, 2007);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('convallis', 'Portugal', 'Forninho', 8, 6, 2012);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('ultrices', 'France', 'Villeneuve-la-Garenne', 7, 14, 2011);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('id', 'France', 'Saint-Étienne', 8, 16, 2011);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('a', 'France', 'Calais', 8, 19, 2006);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('aliquam', 'Portugal', 'Alvito de São Pedro', 7, 11, 2001);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('eu', 'Portugal', 'Alcaria da Serra', 4, 13, 1992);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('potenti', 'Portugal', 'Flor da Rosa', 6, 5, 2000);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('id', 'France', 'Eybens', 5, 18, 1987);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('congue', 'Portugal', 'Agrelo', 5, 20, 2002);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('eget', 'Portugal', 'São Pedro', 8, 8, 1993);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('pellentesque', 'France', 'Tours', 7, 8, 2003);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('cras', 'Germany', 'Halle', 6, 18, 2005);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('justo', 'France', 'Wissous', 4, 9, 1989);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('hendrerit', 'Belgium', 'Mons', 3, 8, 2008);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('at', 'France', 'Pontarlier', 4, 12, 1988);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('tellus', 'Portugal', 'Couço', 4, 5, 2012);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('parturient', 'France', 'Bagneux', 3, 8, 1998);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('nisi', 'United Kingdom', 'Upton', 3, 5, 1994);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('fusce', 'France', 'Béthune', 7, 20, 1999);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('vestibulum', 'Portugal', 'São Mateus', 3, 19, 2008);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('magnis', 'France', 'Annonay', 6, 11, 1990);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('sapien', 'Portugal', 'Bairro', 7, 17, 1984);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('enim', 'Portugal', 'Valença do Douro', 3, 15, 2011);
insert into circuits (name, country, city, lenght, nbTurns, creatDate) values ('mauris', 'Portugal', 'Reguenga', 7, 17, 2010);
